from __future__ import annotations

import base64
import json
import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any
import yaml

from fastapi import APIRouter, HTTPException, BackgroundTasks
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

router = APIRouter()

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
ISO_DIR = PROJECT_ROOT / 'iso'
AUTOINSTALL_DIR = ISO_DIR / 'autoinstall'


class InstallerRequest(BaseModel):
    hostname: str = 'tvtv'
    username: str = 'htpc'
    password: str = 'tvtv'
    realname: str = 'HTPC User'
    timezone: str = 'UTC'
    locale: str = 'en_US.UTF-8'
    keyboard: str = 'us'

    # Display & TV
    display: str = '1080p@60'
    custom_display: str = ''
    wlr_output: str = 'HDMI-A-1'
    ui_scale: int = 13

    # Desktop Shell & Theme
    shell: str = 'labwc'
    theme: str = 'estuary'

    # Audio & Acoustics
    audio: str = 'hdmi'
    audio_engine: str = 'pipewire'
    night_mode: bool = True
    audio_passthrough: bool = False

    # CEC & Remotes
    cec: str = 'yes'
    cec_wake: bool = True
    cec_keys: bool = True
    web_remote: bool = True
    web_remote_port: int = 8080

    # Apps & Ecosystem
    camera_hub: bool = True
    self_updater: bool = True
    samba_share: bool = True
    ssh_server: bool = True
    ai_assistant: bool = True
    kilo_api_key: str = ''

    # Storage & Performance
    storage: str = 'direct'
    target_disk: str = 'auto'
    zram_swap: bool = True

    # Networking
    wifi_ssid: str = ''
    wifi_password: str = ''

    preset: str = 'custom'


InstallerRequest.model_rebuild()


_DISPLAY_MODE_MAP = {
    '1080p@60': '1920x1080@60',
    '1080p@50': '1920x1080@50',
    '1080p@120': '1920x1080@120',
    '4k@60': '3840x2160@60',
    '4k@30': '3840x2160@30',
    '720p@60': '1280x720@60',
}


def _sha512crypt(password: str) -> str:
    """Return a real SHA-512 crypt hash via openssl."""
    try:
        proc = subprocess.run(
            ['openssl', 'passwd', '-6', '-salt', 'tvtv2026', password],
            capture_output=True, text=True, check=False, timeout=5,
        )
        if proc.returncode == 0 and proc.stdout.strip():
            return proc.stdout.strip()
    except Exception:
        pass
    # Fallback to precomputed SHA-512 hash for 'tvtv' with salt 'tvtv2026'
    return "$6$tvtv2026$dbd.bIB6vHtdfhOgQvdigyFFvnyTlomCarkjxFMO3SdVw0Hi1fqzh7UzLQoojVDKOFKYDk6jyuiZjtqfqCnWk1"


def _build_user_data(req: InstallerRequest) -> tuple[str, str]:
    """Generates (user_data_yaml, tv_conf_text)."""
    if req.display == 'custom' and req.custom_display:
        mode = req.custom_display.strip()
    else:
        mode = _DISPLAY_MODE_MAP.get(req.display, '1920x1080@60')

    pw_hash = _sha512crypt(req.password)

    # Base64 encoded tv.conf
    tv_conf = (
        f'# tvtv HTPC Operating System Configuration\n'
        f'# Generated by tvtv Installer\n\n'
        f'export TV_HOSTNAME="{req.hostname}"\n'
        f'export TV_USER="{req.username}"\n'
        f'export WLR_OUTPUT="{req.wlr_output}"\n'
        f'export WLR_MODE="{mode}"\n'
        f'export TV_SCALE="{req.ui_scale}"\n'
        f'export TV_FONT_SIZE="{req.ui_scale}"\n'
        f'export TV_SHELL="{req.shell}"\n'
        f'export TV_THEME="{req.theme}"\n'
        f'export TV_AUDIO="{req.audio}"\n'
        f'export TV_AUDIO_ENGINE="{req.audio_engine}"\n'
        f'export TV_NIGHT_MODE="{1 if req.night_mode else 0}"\n'
        f'export TV_AUDIO_PASSTHROUGH="{1 if req.audio_passthrough else 0}"\n'
        f'export TV_CEC="{req.cec}"\n'
        f'export TV_CEC_WAKE="{1 if req.cec_wake else 0}"\n'
        f'export TV_CEC_KEYS="{1 if req.cec_keys else 0}"\n'
        f'export TV_WEB_REMOTE="{1 if req.web_remote else 0}"\n'
        f'export TV_WEB_REMOTE_PORT="{req.web_remote_port}"\n'
        f'export TV_CAMERA_HUB="{1 if req.camera_hub else 0}"\n'
        f'export TV_SELF_UPDATER="{1 if req.self_updater else 0}"\n'
        f'export TV_STORAGE_LAYOUT="{req.storage}"\n'
        f'export TV_ZRAM="{1 if req.zram_swap else 0}"\n'
        f'export TV_AI_ASSISTANT="{1 if req.ai_assistant else 0}"\n'
        f'export TV_PRESET="{req.preset}"\n\n'
        f'# MPV defaults for this TV\n'
        f'export MPV_SCALE="--video-scale=bilinear"\n'
        f'export MPV_VO="--vo=gpu"\n'
        f'export MPV_HWDEC="--hwdec=auto-safe"\n'
        f'export KIOSK_URL="http://localhost:8000"\n'
    )
    tv_conf_b64 = base64.b64encode(tv_conf.encode()).decode()

    # Wi-Fi lines
    wifi_section = ""
    if req.wifi_ssid:
        wifi_section = f"""      access-points:
        "{req.wifi_ssid}":
          password: "{req.wifi_password}"
      dhcp4: true
"""

    # Package list
    pkg_list = [
        "linux-firmware",
        "linux-generic-hwe-24.04",
        "intel-microcode",
        "iucode-tool",
        "thermald",
        "lm-sensors",
        "curl",
        "wget",
        "git",
        "python3",
        "python3-venv",
        "python3-pip",
        "mpv",
        "yt-dlp",
        "labwc",
        "cage",
        "swaybg",
        "polkitd",
        "seatd",
        "dbus-x11",
        "xwayland",
        "mesa-va-drivers",
        "intel-media-va-driver-non-free",
        "chromium-browser",
        "chromium",
        "cec-utils",
        "ir-keytable",
        "ydotool",
        "ydotoold",
        "playerctl",
        "pipewire",
        "pipewire-audio-client-libraries",
        "wireplumber",
        "alsa-utils",
        "fonts-noto",
        "fonts-noto-color-emoji",
        "xdg-utils",
        "zram-tools",
        "chrony",
        "ethtool",
    ]
    if req.ssh_server:
        pkg_list.append("openssh-server")
    if req.samba_share:
        pkg_list.append("samba")
    if req.shell == 'bigscreen':
        pkg_list.extend(["plasma-bigscreen", "sddm"])
    elif req.shell == 'plasma':
        pkg_list.extend(["plasma-desktop", "sddm"])
    elif req.shell == 'kodi':
        pkg_list.append("kodi")

    late_commands = [
        "curtin in-target --target=/target -- sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT=\"quiet\"/' /etc/default/grub",
        "curtin in-target --target=/target -- update-grub",
        f"curtin in-target --target=/target -- sh -c 'mkdir -p /etc/sudoers.d && printf \"%sudo ALL=(ALL) NOPASSWD: ALL\\n{req.username} ALL=(ALL) NOPASSWD: ALL\\n\" > /etc/sudoers.d/90-tvtv && chmod 0440 /etc/sudoers.d/90-tvtv'",
        "curtin in-target --target=/target -- sh -c 'mkdir -p /etc/xdg && printf \"[Daemon]\\nAutolock=false\\nLockGrace=0\\nLockOnResume=false\\nTimeout=0\\n\" > /etc/xdg/kscreenlockerrc'",
        "curtin in-target --target=/target -- sh -c 'mkdir -p /etc/xdg && printf \"[Wallet]\\nEnabled=false\\nFirst Use=false\\n\" > /etc/xdg/kwalletrc'",
        f"curtin in-target --target=/target -- chage -M 99999 -m 0 {req.username}",
        "curtin in-target --target=/target -- mkdir -p /etc/systemd/logind.conf.d",
        "curtin in-target --target=/target -- sh -c 'printf \"[Login]\\nHandleLidSwitch=ignore\\nHandleLidSwitchExternalPower=ignore\\nHandleLidSwitchDocked=ignore\\nIdleAction=ignore\\n\" > /etc/systemd/logind.conf.d/10-tvtv.conf'",
        "curtin in-target --target=/target -- sh -c 'mkdir -p /etc/modules-load.d && echo uinput > /etc/modules-load.d/uinput.conf'",
        "curtin in-target --target=/target -- sh -c 'printf \"KERNEL==\\\"uinput\\\", SUBSYSTEM==\\\"misc\\\", MODE=\\\"0660\\\", GROUP=\\\"uinput\\\", OPTIONS+=\\\"static_node=uinput\\\"\\n\" > /etc/udev/rules.d/80-uinput.rules'",
        "curtin in-target --target=/target -- sh -c 'printf \"KERNEL==\\\"cec[0-9]*\\\", SUBSYSTEM==\\\"cec\\\", MODE=\\\"0666\\\", GROUP=\\\"dialout\\\"\\nKERNEL==\\\"ttyACM[0-9]*\\\", SUBSYSTEM==\\\"tty\\\", MODE=\\\"0666\\\", GROUP=\\\"dialout\\\"\\nKERNEL==\\\"ttyUSB[0-9]*\\\", SUBSYSTEM==\\\"tty\\\", MODE=\\\"0666\\\", GROUP=\\\"dialout\\\", ATTRS{idVendor}==\\\"1a44\\\"\\n\" > /etc/udev/rules.d/99-cec-adapter.rules'",
        "curtin in-target --target=/target -- sh -c 'printf \"PERCENTAGE=50\\nPRIORITY=100\\n\" > /etc/default/zramswap'",
        f"sh -c 'if [ -d /home/{req.username}/tvtv ]; then cp -a /home/{req.username}/tvtv /target/home/{req.username}/tvtv; fi'",
        f"curtin in-target --target=/target -- bash -c 'if [ ! -d /home/{req.username}/tvtv ]; then git clone --depth 1 https://github.com/dontneedtogotit/tvtv.git /home/{req.username}/tvtv; fi'",
        f"curtin in-target --target=/target -- chown -R {req.username}:{req.username} /home/{req.username}/tvtv",
        f"curtin in-target --target=/target -- bash -c 'mkdir -p /home/{req.username}/.config/tvtv && echo {tv_conf_b64} | base64 -d > /home/{req.username}/.config/tvtv/tv.conf && chown -R {req.username}:{req.username} /home/{req.username}/.config/tvtv'",
    ]
    if req.kilo_api_key:
        late_commands.append(
            f"curtin in-target --target=/target -- bash -c 'mkdir -p /etc/systemd/system/tvtv-yt.service.d && printf \"[Service]\\\\nEnvironment=KILO_API_KEY={req.kilo_api_key}\\\\n\" > /etc/systemd/system/tvtv-yt.service.d/10-kilo.conf'"
        )
    late_commands.append(
        f"curtin in-target --target=/target -- bash /home/{req.username}/tvtv/scripts/setup.sh"
    )

    net_conf: dict[str, Any] = {
        'version': 2,
        'ethernets': {
            'default': {
                'match': {'name': 'e*'},
                'dhcp4': True,
                'dhcp6': False,
            }
        },
        'optional': True,
        'wifi': {'optional': True},
    }
    if req.wifi_ssid:
        net_conf['wifis'] = {
            'wlan0': {
                'optional': True,
                'access-points': {
                    req.wifi_ssid: {'password': req.wifi_password}
                },
                'dhcp4': True,
            }
        }

    storage_conf: dict[str, Any] = {
        'layout': {'name': req.storage} if req.storage != 'lvm' else {'name': 'lvm', 'sizing-policy': 'all'},
        'swap': {'size': 0},
    }

    doc = {
        'autoinstall': {
            'version': 1,
            'locale': req.locale,
            'keyboard': {'layout': req.keyboard, 'variant': ''},
            'network': {'network': net_conf},
            'storage': storage_conf,
            'identity': {
                'hostname': req.hostname,
                'username': req.username,
                'password': pw_hash,
                'realname': req.realname,
                'groups': ['adm', 'cdrom', 'dip', 'plugdev', 'sudo', 'video', 'render', 'audio', 'input', 'nopasswdlogin', 'dialout', 'uinput'],
                'shell': '/bin/bash',
            },
            'ssh': {
                'allow-pw': True,
                'install-server': req.ssh_server,
            },
            'packages': pkg_list,
            'late-commands': late_commands,
            'shutdown': 'reboot',
        },
        'instance-id': 'tvtv-htpc-noble',
        'local-hostname': req.hostname,
    }

    user_data = '#cloud-config\n# tvtv HTPC Operating System (Ubuntu 24.04 LTS Noble Autoinstall)\n' + yaml.dump(doc, sort_keys=False, width=1000)
    return user_data, tv_conf


@router.get('/config')
def get_installer_defaults():
    """Returns available options, presets, themes, shells, and system defaults."""
    presets = [
        {
            "id": "livingroom",
            "name": "70\"+ Living Room TV (Recommended)",
            "description": "Optimized for 70\"+ Samsung/LG/Sony 1080p/4K TVs via HDMI. Includes PipeWire Night Mode, full CEC remote sync, Bigscreen Estuary theme, YouTube player, and Camera Hub.",
            "display": "1080p@60",
            "ui_scale": 13,
            "shell": "bigscreen",
            "theme": "estuary",
            "audio": "hdmi",
            "night_mode": True,
            "cec": "yes",
            "web_remote": True,
            "camera_hub": True,
            "self_updater": True,
            "storage": "direct",
            "zram_swap": True,
        },
        {
            "id": "theater-4k",
            "name": "4K Home Theater (Dolby / DTS Passthrough)",
            "description": "3840x2160 UHD output, direct audio bitstream passthrough for AV receivers, high-bitrate MPV cache, and high-performance Labwc kiosk.",
            "display": "4k@60",
            "ui_scale": 16,
            "shell": "labwc",
            "theme": "midnight",
            "audio": "hdmi",
            "night_mode": False,
            "audio_passthrough": True,
            "cec": "yes",
            "web_remote": True,
            "camera_hub": False,
            "self_updater": True,
            "storage": "direct",
            "zram_swap": True,
        },
        {
            "id": "kiosk",
            "name": "Ultra-Fast Minimal Kiosk",
            "description": "Instant 3-second boot straight into YouTube player on Labwc. Zero background daemons, minimal RAM footprint (<200MB).",
            "display": "1080p@60",
            "ui_scale": 12,
            "shell": "labwc",
            "theme": "oled",
            "audio": "hdmi",
            "night_mode": False,
            "cec": "yes",
            "web_remote": False,
            "camera_hub": False,
            "self_updater": False,
            "storage": "direct",
            "zram_swap": True,
        },
        {
            "id": "full-os",
            "name": "Complete HTPC OS & Surveillance Hub",
            "description": "The complete all-in-one appliance: YouTube, NVR camera monitoring with live alerts, Web Remote, Samba file share, OpenSSH, and self-updater.",
            "display": "1080p@60",
            "ui_scale": 13,
            "shell": "bigscreen",
            "theme": "estuary",
            "audio": "hdmi",
            "night_mode": True,
            "cec": "yes",
            "web_remote": True,
            "camera_hub": True,
            "self_updater": True,
            "samba_share": True,
            "ssh_server": True,
            "storage": "lvm",
            "zram_swap": True,
        },
    ]

    displays = [
        {"id": "1080p@60", "name": "1080p @ 60 Hz (Safe Default / HDMI 1.4a)", "mode": "1920x1080@60"},
        {"id": "1080p@50", "name": "1080p @ 50 Hz (PAL / Europe)", "mode": "1920x1080@50"},
        {"id": "1080p@120", "name": "1080p @ 120 Hz (High Refresh TV)", "mode": "1920x1080@120"},
        {"id": "4k@60", "name": "4K UHD @ 60 Hz (HDMI 2.0+ / 4K TV)", "mode": "3840x2160@60"},
        {"id": "4k@30", "name": "4K UHD @ 30 Hz (HDMI 1.4b 4K TV)", "mode": "3840x2160@30"},
        {"id": "720p@60", "name": "720p @ 60 Hz (Legacy TV)", "mode": "1280x720@60"},
        {"id": "custom", "name": "Custom Resolution (Enter custom width x height @ Hz)", "mode": "custom"},
    ]

    shells = [
        {"id": "labwc", "name": "Labwc Wayland Kiosk (Instant Boot, Lightweight ~10MB)", "desc": "Fastest boot, dedicated fullscreen web kiosk with zero bloat."},
        {"id": "bigscreen", "name": "Plasma Bigscreen (KDE 10-Foot TV Shell)", "desc": "TV-native shell with large D-pad tiles and remote navigation."},
        {"id": "kodi", "name": "Kodi Standalone Media Center", "desc": "Dedicated media center interface with native CEC support."},
        {"id": "plasma", "name": "Plasma Desktop (Standard Linux Desktop)", "desc": "Full desktop environment for combined TV and computing."},
    ]

    themes = [
        {"id": "estuary", "name": "Estuary Slate (LibreELEC Cyan Glow)", "color": "#00d2ff", "bg": "#0f172a"},
        {"id": "midnight", "name": "Midnight Glass (Sapphire Glow)", "color": "#38bdf8", "bg": "#090d16"},
        {"id": "oled", "name": "OLED Stealth (Monochrome & Pure Pitch Black)", "color": "#ffffff", "bg": "#000000"},
        {"id": "cyberpunk", "name": "Cyberpunk Neon (Electric Magenta & Cyan)", "color": "#ff007f", "bg": "#120824"},
        {"id": "sunset", "name": "Sunset Amber (Charcoal & Warm Amber)", "color": "#f59e0b", "bg": "#1c1917"},
        {"id": "emerald", "name": "Emerald Forest (Deep Pine & Mint)", "color": "#10b981", "bg": "#062016"},
    ]

    scales = [
        {"val": 10, "label": "10pt — Bigscreen Native / Compact"},
        {"val": 12, "label": "12pt — Standard 50\"-55\" TV"},
        {"val": 13, "label": "13pt — 65\"-70\" Living Room TV (Recommended)"},
        {"val": 16, "label": "16pt — 75\"-85\" Large Screen"},
        {"val": 20, "label": "20pt — 85\"+ Stadium / High Distance"},
    ]

    return {
        "presets": presets,
        "displays": displays,
        "shells": shells,
        "themes": themes,
        "scales": scales,
        "defaults": InstallerRequest().model_dump(),
    }


@router.get('/disks')
def list_disks():
    """Returns detected physical block devices."""
    disks = []
    try:
        proc = subprocess.run(
            ['lsblk', '-d', '-n', '-J', '-o', 'NAME,SIZE,MODEL,TYPE,TRAN,ROTA'],
            capture_output=True, text=True, check=False, timeout=5,
        )
        if proc.returncode == 0 and proc.stdout.strip():
            data = json.loads(proc.stdout)
            for dev in data.get('blockdevices', []):
                if dev.get('type') == 'disk':
                    name = dev.get('name', '')
                    model = (dev.get('model') or '').strip()
                    size = dev.get('size', '')
                    tran = dev.get('tran') or 'nvme' if 'nvme' in name else 'sata'
                    disks.append({
                        'device': f'/dev/{name}',
                        'name': name,
                        'size': size,
                        'model': model or 'Internal Drive',
                        'transport': tran,
                    })
    except Exception:
        pass
    if not disks:
        disks = [
            {'device': '/dev/nvme0n1', 'name': 'nvme0n1', 'size': '500G', 'model': 'NVMe SSD (Auto-detected)', 'transport': 'nvme'},
            {'device': '/dev/sda', 'name': 'sda', 'size': '256G', 'model': 'SATA SSD / HDD', 'transport': 'sata'},
        ]
    return {'disks': disks}


@router.get('/wifi-scan')
def scan_wifi():
    """Scans and returns nearby Wi-Fi SSIDs."""
    networks = []
    try:
        proc = subprocess.run(
            ['nmcli', '-t', '-f', 'SSID,SIGNAL,SECURITY', 'dev', 'wifi', 'list'],
            capture_output=True, text=True, check=False, timeout=8,
        )
        if proc.returncode == 0:
            seen = set()
            for line in proc.stdout.splitlines():
                parts = line.split(':')
                if parts and parts[0] and parts[0] not in seen:
                    seen.add(parts[0])
                    signal = int(parts[1]) if len(parts) > 1 and parts[1].isdigit() else 75
                    sec = parts[2] if len(parts) > 2 else "WPA2"
                    networks.append({'ssid': parts[0], 'signal': signal, 'security': sec})
    except Exception:
        pass
    return {'networks': networks}


@router.post('/generate')
def generate_installer(req: InstallerRequest):
    """Generates the Ubuntu autoinstall cloud-config YAML and saves it."""
    user_data, tv_conf = _build_user_data(req)

    out_path = '/tmp/tvtv-installer-user-data.yaml'
    try:
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, 'w') as f:
            f.write(user_data)
    except Exception as e:
        raise HTTPException(500, f'Failed to write installer config: {e}')

    # Also update in-tree iso/autoinstall/user-data if available
    in_tree_autoinstall = AUTOINSTALL_DIR / 'user-data'
    try:
        if AUTOINSTALL_DIR.exists():
            in_tree_autoinstall.write_text(user_data)
    except Exception:
        pass

    return {
        'status': 'ok',
        'path': out_path,
        'user_data': user_data,
        'tv_conf': tv_conf,
        'message': 'Autoinstall configuration generated successfully.',
    }


@router.get('/preview')
def preview_installer(
    hostname: str = 'tvtv',
    username: str = 'htpc',
    display: str = '1080p@60',
    shell: str = 'labwc',
    theme: str = 'estuary',
    audio: str = 'hdmi',
    night_mode: bool = True,
    storage: str = 'direct',
    cec: str = 'yes',
    preset: str = 'livingroom',
):
    """Returns a generated preview without writing to disk."""
    req = InstallerRequest(
        hostname=hostname, username=username, display=display,
        shell=shell, theme=theme, audio=audio, night_mode=night_mode,
        storage=storage, cec=cec, preset=preset,
    )
    user_data, tv_conf = _build_user_data(req)
    return {'user_data': user_data, 'tv_conf': tv_conf}


_ISO_BUILD_STATUS = {
    'running': False,
    'progress': '',
    'log': [],
    'output_iso': '',
    'error': '',
}


def _run_remaster_task():
    global _ISO_BUILD_STATUS
    _ISO_BUILD_STATUS['running'] = True
    _ISO_BUILD_STATUS['error'] = ''
    _ISO_BUILD_STATUS['progress'] = 'Starting ISO remastering...'

    remaster_script = ISO_DIR / 'remaster.sh'
    if not remaster_script.exists():
        _ISO_BUILD_STATUS['running'] = False
        _ISO_BUILD_STATUS['error'] = f'Remaster script not found at {remaster_script}'
        return

    try:
        proc = subprocess.Popen(
            ['bash', str(remaster_script)],
            cwd=str(PROJECT_ROOT),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        log_lines = []
        if proc.stdout:
            for line in proc.stdout:
                clean = line.strip()
                if clean:
                    log_lines.append(clean)
                    _ISO_BUILD_STATUS['progress'] = clean
                    _ISO_BUILD_STATUS['log'] = log_lines[-50:]
        proc.wait()
        if proc.returncode == 0:
            _ISO_BUILD_STATUS['progress'] = 'ISO build complete!'
            _ISO_BUILD_STATUS['output_iso'] = str(PROJECT_ROOT / 'iso-output' / 'tvtv-installer.iso')
        else:
            _ISO_BUILD_STATUS['error'] = f'Remaster process exited with code {proc.returncode}'
    except Exception as e:
        _ISO_BUILD_STATUS['error'] = str(e)
    finally:
        _ISO_BUILD_STATUS['running'] = False


@router.post('/bake-iso')
def bake_iso(background_tasks: BackgroundTasks):
    """Triggers ISO remastering in background."""
    global _ISO_BUILD_STATUS
    if _ISO_BUILD_STATUS['running']:
        return {'status': 'already_running', 'progress': _ISO_BUILD_STATUS['progress']}
    background_tasks.add_task(_run_remaster_task)
    return {'status': 'started', 'message': 'ISO remastering started in background.'}


@router.get('/status')
def get_status():
    """Returns current installer & ISO build status."""
    return {
        'status': 'ok',
        'iso_build': _ISO_BUILD_STATUS,
        'has_xorriso': bool(shutil.which('xorriso') or (ISO_DIR / 'iso-tools' / 'usr' / 'bin' / 'xorriso').exists()),
        'has_user_data': (AUTOINSTALL_DIR / 'user-data').exists(),
    }
