#!/usr/bin/env bash
# tv-profile.sh — TV display & appliance profile manager for tvtv OS
# Applies a reproducible boot configuration for Intel NUC + 70"+ TV.
set -euo pipefail

PROFILE_DIR="/home/htpc/.config/tvtv"
mkdir -p "$PROFILE_DIR"

MODE="${1:-1920x1080@60}"
SCALE="${2:-13}"
AUDIO="${3:-hdmi}"
CEC="${4:-yes}"
THEME="${5:-estuary}"
SHELL_TYPE="${6:-labwc}"

cat > "$PROFILE_DIR/tv.conf" <<EOF
# tvtv HTPC Operating System Configuration
# Generated by tv-profile.sh

export TV_USER="htpc"
export WLR_OUTPUT="HDMI-A-1"
export WLR_MODE="$MODE"
export TV_SCALE="$SCALE"
export TV_FONT_SIZE="$SCALE"
export TV_AUDIO="$AUDIO"
export TV_NIGHT_MODE="1"
export TV_CEC="$CEC"
export TV_THEME="$THEME"
export TV_SHELL="$SHELL_TYPE"

# MPV defaults for 70"+ TV
export MPV_SCALE="--video-scale=bilinear"
export MPV_VO="--vo=gpu"
export MPV_HWDEC="--hwdec=auto-safe"
export KIOSK_URL="http://localhost:8000"
EOF

echo "TV profile written to $PROFILE_DIR/tv.conf"
