#!/usr/bin/env bash
# tvtv-yt TV boot profile
# Applies a minimal, reproducible boot configuration for the NUC + 2013 Samsung TV.
# Run on the NUC after the base setup.

set -euo pipefail

PROFILE_DIR="/home/htpc/.config/tvtv"
mkdir -p "$PROFILE_DIR"

# Default TV profile for 2013 Samsung 70" via HDMI 1.4a
# These can be overridden by the user if EDID detection finds something else.
cat > "$PROFILE_DIR/tv.conf" <<'EOF'
# tvtv-yt TV profile
# Generated by scripts/tv-profile.sh

# Display output (Labwc / wlroots)
WLR_OUTPUT="HDMI-A-1"
WLR_MODE="1920x1080@60"

# MPV defaults for this TV
MPV_SCALE="--video-scale=bilinear"
MPV_VO="--vo=gpu"
MPV_HWDEC="--hwdec=auto-safe"

# Chromium kiosk behavior
KIOSK_URL="http://localhost:8000"
EOF

echo "TV profile written to $PROFILE_DIR/tv.conf"
echo "Edit that file if detect-tv.sh found a different preferred mode."
